# Generated by Django 3.2 on 2021-04-18 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Algorithm_Name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Algorithm_Video_Title', models.CharField(default=None, max_length=150)),
                ('Algorithm_Video_URL', models.URLField(default=None)),
                ('Algorithms_Video_Image', models.ImageField(default=None, upload_to='static/')),
                ('Algorithm_Name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Algorithms.algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Algorithm_Question_Title', models.CharField(default=None, max_length=100)),
                ('Algorithm_Question_Link', models.URLField(default=None)),
                ('Algorithm_Question_Difficulty', models.IntegerField(default=None)),
                ('Algorithm_Question_Editorial', models.URLField(blank=True, default=None, null=True)),
                ('Algorithm_Name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Algorithms.algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Algorithm_Blog_Title', models.CharField(default=None, max_length=150)),
                ('Algorithm_Blog_URL', models.URLField(default=None)),
                ('Algorithm_Name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Algorithms.algorithm')),
            ],
        ),
    ]
