# Generated by Django 3.1.7 on 2021-04-01 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataStructure_Name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataStructureVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataStructure_Video_Title', models.CharField(default=None, max_length=150)),
                ('DataStructure_Video_URL', models.URLField(default=None)),
                ('DataStructures_Video_Image', models.ImageField(default=None, upload_to='static/')),
                ('DataStructure_Name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DataStructures.datastructure')),
            ],
        ),
        migrations.CreateModel(
            name='DataStructureQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataStructure_Question_Title', models.CharField(default=None, max_length=100)),
                ('DataStructure_Question_Link', models.URLField(default=None)),
                ('DataStructure_Question_Difficulty', models.IntegerField(default=None)),
                ('DataStructure_Question_Editorial', models.URLField(blank=True, default=None, null=True)),
                ('DataStructure_Name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DataStructures.datastructure')),
            ],
        ),
        migrations.CreateModel(
            name='DataStructureBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataStructure_Blog_Title', models.CharField(default=None, max_length=150)),
                ('DataStructure_Blog_URL', models.URLField(default=None)),
                ('DataStructure_Name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DataStructures.datastructure')),
            ],
        ),
    ]
