# Generated by Django 3.1.4 on 2021-03-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithms', '0002_auto_20210326_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmsquestion',
            name='Algoritm_Question_Title',
        ),
        migrations.AddField(
            model_name='algorithmsquestion',
            name='Algorithm_Question_Title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
