# Generated by Django 3.1.4 on 2021-03-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithms', '0003_auto_20210327_1236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlgorithmsBlog',
            new_name='AlgorithmBlog',
        ),
        migrations.RenameModel(
            old_name='AlgorithmsQuestion',
            new_name='AlgorithmQuestion',
        ),
        migrations.RenameModel(
            old_name='AlgorithmsVideo',
            new_name='AlgorithmVideo',
        ),
    ]
